default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

development:
  <<: *default
  database: roadpass_digital_development

test:
  <<: *default
  database: roadpass_digital_test

production:
  <<: *default
  database: roadpass_digital_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>